---
- name: Testing andrewrothstein.cure
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'cue version'
      ansible.builtin.command: /usr/local/bin/cue version
      changed_when: false
      register: cue_test_output
    - name: Output of 'cue version'
      ansible.builtin.debug:
        msg: '{{ cue_test_output.stdout }}'
