---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install at {{ cue_exe }}
  become: true
  stat:
    path: '{{ cue_exe }}'
  changed_when: false
  register: cue_binary
- when: not cue_binary.stat.exists
  block:
    - name: download {{ cue_url }} to {{ cue_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ cue_url }}'
        dest: '{{ cue_tmp_archive }}'
        mode: 0644
        checksum: '{{ cue_checksum }}'
    - name: mkdir {{ cue_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ cue_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ cue_tmp_archive }} to {{ cue_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ cue_tmp_archive }}'
        dest: '{{ cue_install_dir }}'
        creates: '{{ cue_exe }}'
  always:
    - name: rm -f {{ cue_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ cue_tmp_archive }}'
        state: absent
- name: linking {{ cue_link }} to {{ cue_exe }}
  become: true
  become_user: root
  file:
    src: '{{ cue_exe }}'
    dest: '{{ cue_link }}'
    state: link
